[package]
name = "orga"
version = "0.3.0"
authors = ["Matt Bell <mappum@gmail.com>"]
edition = "2021"
description = "State machine engine"
license = "MIT"

[dependencies]
abci2 = { git = "https://github.com/nomic-io/abci2", rev = "f8e218c4d7170b2cec85e21b923644871a44d1b0", optional = true }
merk = { git = "https://github.com/nomic-io/merk", rev = "a2e46ed40c7b7eeaaed7a94654c18413728f7b8d", optional = true, default-features = false }
tendermint-rpc = { version = "0.23.5", features = ["http-client"], optional = true }
tendermint = { version = "0.23.5", optional = true }
tendermint-proto = { version = "0.23.5", optional = true }
orga-macros = { path = "macros", version = "0.2.4" }
seq-macro = "0.1.4"
log = "0.4.8"
hex-literal = "0.3.3"
sha2 = "0.9.5"
is_executable = { version = "1.0.1", optional = true }
reqwest = {version = "0.11.4", features = ["blocking"]}
flate2 = "1.0.20"
tar = "0.4.33"
ed = "0.3.0" 
toml_edit = "0.2.0"
prost = {version = "0.9", optional = true}
home = { version = "0.5.3", optional = true }
ed25519-dalek = "1"
thiserror = "1.0.29"
bech32 = "0.8.1"
async-trait = "0.1.51"
futures-lite = "1.12.0"
num-rational = "0.4.0"
num-traits = "0.2.14"
rust_decimal = "1.18"
ripemd = "0.1.0"
web-sys = { version = "0.3.55", features = ["Window", "Storage"] }
rust_decimal_macros = "1.18"
js-sys = "0.3.55"
wasm-bindgen-futures = "0.4.28"
wasm-bindgen = "0.2.78"
hex = "0.4.3"
base64 = "0.13.0"
secp256k1 = { version = "0.22.1", features = ["bitcoin_hashes"] }
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"
v2 = { git = "https://github.com/nomic-io/orga", branch = "v2-legacy-testnet", features = ["merk-full", "abci"], package = "orga", optional = true }

[dev-dependencies]
tempdir = "0.3.7"
tokio = { version = "1.11.0", features = ["rt", "macros"] }
mutagen = {git = "https://github.com/llogiq/mutagen"}
serial_test = "0.5.1"

[package.metadata.docs.rs]
features = ["abci", "merk/full"]

[features]
abci = ["abci2", "tendermint", "tendermint-rpc", "tendermint-proto", "prost", "is_executable", "home", "secp256k1/rand-std", "v2"]
merk-verify = ["merk/verify"]
merk-full = ["merk/full"]
state-sync = []

[profile.release]
lto = true

