[package]
name = "orga"
version = "0.1.10"
authors = ["Matt Bell <mappum@gmail.com>"]
edition = "2018"
description = "State machine engine"
license = "MIT"

[dependencies]
failure = "0.1.8"
abci2 = { git = "https://github.com/nomic-io/abci2", optional = true }
merk = { git = "https://github.com/nomic-io/merk", rev = "a613a054001f28b9f23d7576ae92ec8a2922168c", optional = true }
tendermint-rpc = { version = "0.21.0", features = ["http-client"], optional = true }
tendermint = { version = "0.21.0", optional = true }
tendermint-proto = { version = "0.21.0", optional = true }
orga-macros = { path = "macros", version = "0.1.0" }
seq-macro = "0.1.4"
log = "0.4.8"
blocking = "0.4.7"
ed = "0.1.3"
hex-literal = "0.3.3"
sha2 = "0.9.5"
is_executable = "1.0.1"
reqwest = {version = "0.11.4", features = ["blocking"]}
flate2 = "1.0.20"
tar = "0.4.33"

[dev-dependencies]
tempdir = "0.3.7"

[package.metadata.docs.rs]
features = ["abci", "merk"]

[features]
abci = ["abci2", "tendermint", "tendermint-rpc", "tendermint-proto"]

[profile.release]
lto = true

[[example]]
name = "counter"
required-features = ["merk", "abci"]

[[example]]
name = "counter_replicant"
required-features = ["merk", "abci"]
