[package]
name = "orga-macros"
version = "0.1.0"
authors = ["Matt Bell <mappum@gmail.com>"]
edition = "2018"
description = "Macros for the orga crate"
license = "MIT"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.17"
proc-macro2 = "1.0.10"
quote = "1.0.3"
